---
# tasks file for ansible.bitlocker

- name: add OS specific variables
  include_vars: '{{ loop_vars }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml'
        - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
        - '{{ ansible_system }}.yml'
        - 'defaults.yml'
      paths:
        - 'vars'
  loop_control:
    loop_var: loop_vars
  tags:
    - configuration
    - packages

- win_tpm_facts:

- win_bitlocker_facts:

- name: Configure BitLocker
  win_bitlocker:
    mount: '{{ bitlocker_mount }}'
    state: '{{ bitlocker_state }}'
    encryption: '{{ bitlocker_encryption }}'
    keyprotector: '{{ bitlocker_keyprotector }}'
    backup_to_ad: '{{ bitlocker_backup_to_ad }}'
    hardware_encryption: '{{ bitlocker_hardware_encryption }}'
    skip_hardware_test: '{{ bitlocker_skip_hardware_test }}'
    used_space_only: '{{ bitlocker_used_space_only }}'
  when: ansible_tpm.TpmPresent

...
